import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { tmpdir } from "node:os";
import { Workspace, RevisionConflictError } from "@arbor/arborsync";

let root: string;
let state: string;
let workspace: Workspace;

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), "arbor-workspace-"));
  state = await mkdtemp(join(tmpdir(), "arbor-state-"));
  process.env.ARBOR_DATA_HOME = state;
  await writeFile(join(root, "notes.md"), "---\ntitle: Notes\n---\n▸ Ideas\n  First\n");
  await mkdir(join(root, "folder"));
  await writeFile(join(root, "folder", "child.md"), "Child body\n");
  await mkdir(join(root, ".claude", "worktrees"), { recursive: true });
  await writeFile(join(root, ".claude", "worktrees", "visible.md"), "Workspace discovery marker\n");
  await mkdir(join(root, ".build", "artifacts"), { recursive: true });
  await writeFile(join(root, ".build", "artifacts", "hidden.md"), "Generated build marker\n");
  workspace = await Workspace.open(root);
});

afterAll(async () => {
  await workspace[Symbol.asyncDispose]();
  await rm(root, { recursive: true, force: true });
  await rm(state, { recursive: true, force: true });
});

describe("workspace service", () => {
  test("browses pages and directories", async () => {
    const rootNode = await workspace.node("/");
    expect(rootNode.children?.map((item) => item.name)).toContain("notes");
    expect(rootNode.children?.map((item) => item.name)).toContain(".claude");
    expect(rootNode.children?.map((item) => item.name)).not.toContain(".build");
    const leaf = await workspace.node("/notes");
    expect(leaf.document?.blocks[0]?.type).toBe("toggle");
    expect((await workspace.node("/notes.md")).path).toBe("/notes");
  });

  test("keeps generated collection types in private workspace state", async () => {
    const declarationPath = workspace.generatedTypeDeclarationPath();
    expect(relative(root, declarationPath).startsWith("..")).toBe(true);
    expect(await readFile(declarationPath, "utf8")).toContain('declare module "arbor/runtime"');
    await expect(stat(join(root, ".arbor"))).rejects.toThrow();

    const collection = join(root, "typed");
    const schemaPath = join(collection, "schema.ts");
    await mkdir(collection);
    await writeFile(schemaPath, 'import { z } from "zod"; export const schema = z.object({ title: z.string() });\n');
    await writeFile(join(collection, "_store.csv"), "title\nExample\n");
    await workspace.generateTypes();

    const generated = await readFile(declarationPath, "utf8");
    const schemaImport = generated.match(/import type \{ schema as Schema0 \} from ("[^"]+");/);
    expect(schemaImport).not.toBeNull();
    expect(resolve(dirname(declarationPath), JSON.parse(schemaImport![1]!))).toBe(join(workspace.root, "typed", "schema.ts"));
    expect(generated).toContain('"/typed": Collection<z.infer<typeof Schema0>>;');

    await mkdir(join(root, ".arbor"));
    await writeFile(join(root, ".arbor", "tree.gen.d.ts"), "// Generated by arbor dev. Do not edit.\nexport {};\n");
    await workspace.generateTypes();
    await expect(stat(join(root, ".arbor", "tree.gen.d.ts"))).rejects.toThrow();
    await expect(stat(join(root, ".arbor"))).rejects.toThrow();
  });

  test("keeps Markdown collection rows out of the directory document", async () => {
    const collection = join(root, "records");
    await mkdir(collection);
    await writeFile(join(collection, "schema.ts"), 'import { z } from "zod"; export const schema = z.object({ title: z.string() });\n');
    await writeFile(join(collection, "_index.md"), "About the records.\n");
    await writeFile(join(collection, "one.md"), "---\ntitle: One\n---\nRow body.\n");

    const node = await workspace.node("/records");
    expect(node.kind).toBe("collection");
    expect(node.document?.source).toBe("About the records.\n");
    expect(node.children?.some((child) => child.path === "/records/one")).toBe(true);
  });

  test("writes exact source and enforces revision CAS", async () => {
    const node = await workspace.node("/notes");
    const source = "---\ntitle: Notes\n---\n▸ Changed\n  First\n";
    const saved = await workspace.write("/notes", { baseRevision: node.revision, source });
    expect(saved.document?.frontmatter.id).toBeUndefined();
    expect(saved.document?.source).toBe(source);
    expect(await readFile(join(root, "notes.md"), "utf8")).toContain("▸ Changed");
    await expect(workspace.write("/notes", { baseRevision: node.revision, source })).rejects.toBeInstanceOf(RevisionConflictError);
  });

  test("materializes a directory page on first write", async () => {
    const node = await workspace.node("/folder");
    await workspace.write("/folder", { baseRevision: node.revision, source: "About this folder\n" });
    const stored = await readFile(join(root, "folder", "_index.md"), "utf8");
    expect(stored).toContain("About this folder");
    expect(stored).toContain("[child](child)");
    expect((await workspace.node("/folder/_index.md")).path).toBe("/folder");
  });

  test("reports body state and unambiguous child identity", async () => {
    const notes = await workspace.snapshot({ tree: "local", path: "/notes" });
    expect(notes.bodyState).toBe("stored");
    expect(notes.bodyOrigin).toBe("sibling");
    expect(notes.ref.pageID).toBeUndefined();

    const materialized = await workspace.snapshot({ tree: "local", path: "/folder" });
    expect(materialized.bodyState).toBe("stored");
    expect(materialized.bodyOrigin).toBe("index");

    await mkdir(join(root, "plain"));
    const implicit = await workspace.snapshot({ tree: "local", path: "/plain" });
    expect(implicit.bodyState).toBe("implicit");
    expect(implicit.bodyOrigin).toBeUndefined();
    expect(implicit.document?.blocks).toEqual([]);

    const listing = await workspace.children({ tree: "local", path: "/" });
    const child = listing.items.find((item) => item.path === "/notes");
    expect(child?.pageID).toBeUndefined();
    expect(listing.items.find((item) => item.path === "/plain")?.pageID).toBeUndefined();
  });

  test("ensureDocumentIdentity mints lazily, no-ops when present, and replays idempotently", async () => {
    await mkdir(join(root, "bodyless"));
    const before = await workspace.snapshot({ tree: "local", path: "/bodyless" });
    expect(before.bodyState).toBe("implicit");
    expect(before.ref.pageID).toBeUndefined();

    const request = {
      mutationID: "identity-test-0001",
      operations: [{
        op: "ensureDocumentIdentity" as const,
        ref: { tree: "local", path: "/bodyless" },
        baseContentRevision: before.contentRevision!,
      }] as [never] & { 0: unknown },
    };
    const receipt = await workspace.executeMutation(request as never);
    const effect = receipt.effects[0]!;
    expect(effect.pageID).toMatch(/^[a-z0-9]{6}$/);
    const materialized = await readFile(join(root, "bodyless", "_index.md"), "utf8");
    expect(materialized).toContain(`id: ${effect.pageID}`);
    expect(materialized.trim().endsWith("---")).toBe(true);

    const replayed = await workspace.executeMutation(request as never);
    expect(replayed).toEqual(receipt);

    const after = await workspace.snapshot({ tree: "local", path: "/bodyless" });
    const again = await workspace.executeMutation({
      mutationID: "identity-test-0002",
      operations: [{
        op: "ensureDocumentIdentity",
        ref: { tree: "local", path: "/bodyless" },
        baseContentRevision: "sha256:stale-is-fine-for-a-no-op",
      }],
    } as never);
    expect(again.effects[0]?.pageID).toBe(effect.pageID);
    expect(again.effects[0]?.contentRevision).toBe(after.contentRevision!);
  });

  test("rename and trash preserve and report document identity", async () => {
    await writeFile(join(root, "unnamed.md"), "No identity yet\n");
    const receipt = await workspace.executeMutation({
      mutationID: "identity-rename-0001",
      operations: [{ op: "rename", ref: { tree: "local", path: "/unnamed" }, name: "named" }],
    } as never);
    const moved = receipt.effects.find((item) => item.path === "/named");
    expect(moved?.pageID).toMatch(/^[a-z0-9]{6}$/);
    expect(await readFile(join(root, "named.md"), "utf8")).toContain(`id: ${moved!.pageID}`);

    const trashed = await workspace.executeMutation({
      mutationID: "identity-trash-0001",
      operations: [{ op: "trash", refs: [{ tree: "local", path: "/named" }] }],
    } as never);
    expect(trashed.effects.some((item) => item.pageID === moved!.pageID)).toBe(true);
  });

  test("soft deletes and restores", async () => {
    const deleted = await workspace.delete("/folder/child");
    expect(deleted.trashPath).toStartWith("/Trash/folder/child");
    await expect(stat(join(root, "folder", "child.md"))).rejects.toThrow();
    await mkdir(join(root, "folder", "child"));
    await expect(workspace.restore(deleted.trashPath)).rejects.toThrow("Destination already exists");
    await rm(join(root, "folder", "child"), { recursive: true });
    const restored = await workspace.restore(deleted.trashPath);
    expect(restored.path).toBe("/folder/child");
    expect(await readFile(join(root, "folder", "child.md"), "utf8")).toContain("Child body");
  });

  test("stores content-addressed assets", async () => {
    const asset = await workspace.addAsset("/folder", "picture.png", new TextEncoder().encode("image"));
    expect(asset.path).toMatch(/^\/Assets\/[a-f0-9]{16}\.png$/);
    expect(asset.markdownPath).toStartWith("/Assets/");
    expect(asset.markdownPath).toBe(asset.path);
  });

  test("searches indexed content", async () => {
    await new Promise((resolve) => setTimeout(resolve, 100));
    expect(workspace.search("Changed").some((item) => item.path === "/notes")).toBe(true);
    expect(workspace.search("discovery marker").some((item) => item.path === "/.claude/worktrees/visible")).toBe(true);
    expect(workspace.search("build marker")).toEqual([]);
  });

  test("uses a sibling Markdown body for a directory and blocks two bodies", async () => {
    const duplicateRoot = await mkdtemp(join(tmpdir(), "arbor-duplicate-"));
    const duplicateState = await mkdtemp(join(tmpdir(), "arbor-duplicate-state-"));
    process.env.ARBOR_DATA_HOME = duplicateState;
    let duplicateWorkspace: Workspace | null = null;
    try {
      await writeFile(join(duplicateRoot, "same.md"), "Leaf\n");
      await mkdir(join(duplicateRoot, "same"));
      await writeFile(join(duplicateRoot, "same", "child.md"), "Child\n");
      duplicateWorkspace = await Workspace.open(duplicateRoot);
      const rootNode = await duplicateWorkspace.node("/");
      expect(rootNode.children?.filter((child) => child.path === "/same")).toHaveLength(1);
      const same = await duplicateWorkspace.node("/same");
      expect(same.kind).toBe("directory");
      expect(same.document?.bodySource).toBe("Leaf\n\n[child](child)\n");
      await duplicateWorkspace[Symbol.asyncDispose]();
      duplicateWorkspace = null;

      await writeFile(join(duplicateRoot, "same", "_index.md"), "Directory\n");
      duplicateWorkspace = await Workspace.open(duplicateRoot);
      const duplicate = await duplicateWorkspace.node("/same");
      expect(duplicate.diagnostics.some((item) => item.code === "duplicate-body-representation")).toBe(true);
      await expect(duplicateWorkspace.write("/same", { baseRevision: duplicate.revision, source: duplicate.document?.source ?? "" })).rejects.toThrow("competing bodies");
    } finally {
      await duplicateWorkspace?.[Symbol.asyncDispose]();
      process.env.ARBOR_DATA_HOME = state;
      await rm(duplicateRoot, { recursive: true, force: true });
      await rm(duplicateState, { recursive: true, force: true });
    }
  });
});
