// Generated by arbor dev. Do not edit.
import type { z } from "zod";
import type { schema as Schema0 } from "../tests/fixtures/workspace/books/schema.ts";
type Collection<T> = { readonly __row?: T };
type Database<T> = { readonly __tables?: T };
declare module "arbor/runtime" {
  interface TreeRegistry {
    "/tests/fixtures/workspace/books": Collection<z.infer<typeof Schema0>>;
  }
}
export {};
