import {
  checkpointBatchSchema, checkpointBatchResponseSchema,
  type CheckpointBatchRequest, type CheckpointBatchResponse,
  checkpointSchema,
  checkpointResponseSchema,
  type CheckpointRequest,
  type CheckpointResponse,
} from "./checkpoint.ts";
import {
  isIntentRequest,
  parseIntentResponse,
  parseIntentRequest,
  type IntentRequestInput,
  type IntentResponse,
} from "./intent-model.ts";
import { z } from "zod";
import { mergeSummarySchema } from "./summary.ts";
import { OBJECT_HASH } from "./state-value.ts";

const hash = z.string().regex(OBJECT_HASH);
const path = z.string().refine(
  (value) =>
    value === "/" ||
    (value.startsWith("/") &&
      value
        .slice(1)
        .split("/")
        .every(
          (part) =>
            part && part !== "." && part !== ".." && !/[\\\0]/.test(part)
        ))
);
const material = z.object({ object: hash }).strict();
const rule = z
  .object({ id: z.string().min(1), revision: z.literal(1) })
  .strict();
const treeRequest = z
  .object({ base: material, current: material, rules: rule, kind: z.literal("tree"), incoming: material })
  .strict();

export type ProjectionRequest = z.infer<typeof treeRequest>;

export type MergeRequest =
  | ProjectionRequest
  | IntentRequestInput
  | CheckpointRequest
  | CheckpointBatchRequest;
export function parseRequest(raw: unknown): MergeRequest {
  if (raw && typeof raw === "object" && "kind" in raw && raw.kind === "checkpoint-batch")
    return checkpointBatchSchema.parse(raw);
  if (
    raw &&
    typeof raw === "object" &&
    "kind" in raw &&
    raw.kind === "checkpoint"
  )
    return checkpointSchema.parse(raw);
  if (isIntentRequest(raw)) return parseIntentRequest(raw);
  return treeRequest.parse(raw);
}

const reason = z.enum([
  "node-conflict",
  "binary-conflict",
  "path-kind-conflict",
  "nested-boundary-conflict",
  "account-configuration",
  "page-id-move-conflict",
  "collection-file-row-conflict",
  "collection-file-schema-conflict",
  "collection-file-constraint-conflict",
  "frontmatter-conflict",
  "invalid-markdown-fence",
]);
const decision = z
  .object({
    kind: z.literal("conflict"),
    path,
    reason,
    scope: z.enum(["entry", "directory"]),
  })
  .strict();
const response = z
  .object({
    result: material,
    decisions: z.array(decision),
    objects: z.array(hash),
    evidence: z.object({ rule, summary: mergeSummarySchema.optional() }).strict(),
  })
  .strict();
export type ProjectionResponse = z.infer<typeof response>;

/** The transport carries references only. Generated bytes live in the job store. */
export type MergeResponse =
  | ProjectionResponse
  | IntentResponse
  | CheckpointResponse
  | CheckpointBatchResponse;
export function parseResponse(raw: unknown, request: CheckpointBatchRequest): CheckpointBatchResponse;
export function parseResponse(
  raw: unknown,
  request: CheckpointRequest
): CheckpointResponse;
export function parseResponse(
  raw: unknown,
  request: ProjectionRequest
): ProjectionResponse;
export function parseResponse(
  raw: unknown,
  request: IntentRequestInput
): Extract<IntentResponse, { outcome: "evaluated" }>;
export function parseResponse(
  raw: unknown,
  request: MergeRequest
):
  | ProjectionResponse
  | Extract<IntentResponse, { outcome: "evaluated" }>
  | CheckpointResponse
  | CheckpointBatchResponse;
export function parseResponse(
  raw: unknown,
  request: MergeRequest
):
  | ProjectionResponse
  | Extract<IntentResponse, { outcome: "evaluated" }>
  | CheckpointResponse
  | CheckpointBatchResponse {
  if (request.kind === "checkpoint-batch") {
    const value = checkpointBatchResponseSchema.parse(raw);
    if (value.checkpoints.length !== request.steps.length
      || value.checkpoints.some((ref, index) => ref.object !== request.steps[index]!.projection)
      || value.result.object !== value.checkpoints.at(-1)!.object
      || value.result.state !== value.checkpoints.at(-1)!.state
      || new Set(value.objects).size !== value.objects.length)
      throw new Error("Checkpoint batch does not match accepted history");
    return value;
  }
  if (request.kind === "checkpoint") {
    const value = checkpointResponseSchema.parse(raw);
    if (
      value.result.object !== request.projection &&
      !(
        request.conflictProjection === "current" &&
        value.result.object === request.current.object
      )
    )
      throw new Error("Checkpoint projection mismatch");
    return value;
  }
  if (isIntentRequest(request)) return parseIntentResponse(raw, request);
  const value = response.parse(raw);
  if (
    value.evidence.rule.id !== request.rules.id ||
    value.evidence.rule.revision !== request.rules.revision ||
    new Set(value.objects).size !== value.objects.length
  )
    throw new Error("Merge response does not match request");
  // Summaries are persisted as evidence: the schema accepts no arbitrary
  // executable output, and account rules must report their own version.
  const summary = value.evidence.summary;
  if (
    summary &&
    ((request.rules.id.startsWith("account-config") &&
      summary.version !== request.rules.id) ||
      (request.rules.id === "tree-default" &&
        summary.version.startsWith("account-config")))
  )
    throw new Error("Unexpected merge evidence");
  return value;
}

export { isIntentRequest } from "./intent-model.ts";
