import { mkdir, stat } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { writeAtomic, type WorkspaceDiscovery, type WorkspaceFS } from "@arbor/fs";
import type { NodeProviderRouter } from "./node-provider-router.ts";

export const GENERATED_TYPES_HEADER = "// Generated by arbor open. Do not edit.";

/** The workspace state `generateTreeTypes` reads. */
export interface GenerateTreeTypesOptions {
  root: string;
  stateDirectory: string;
  fs: Pick<WorkspaceFS, "discoverRecursively">;
  provider: Pick<NodeProviderRouter, "schemaTypes">;
  discovery?: WorkspaceDiscovery;
}

export async function generateTreeTypes(options: GenerateTreeTypesOptions): Promise<void> {
  const { root, stateDirectory, fs, provider, discovery } = options;
  const target = generatedTypeDeclarationPath(stateDirectory);
  const imports: string[] = [];
  const declarations: string[] = [];
  const mappings: string[] = [];
  let schemaIndex = 0;
  let databaseIndex = 0;
  let temporaryFailure = false;
  const snapshot = discovery ?? await fs.discoverRecursively();
  for (const directory of snapshot.directories) {
    if (directory.absolutePath === root) continue;
    if (directory.childNames.has("schema.ts") || directory.childNames.has("_store.postgres")) {
      const absolute = directory.absolutePath;
      const shape = await provider.schemaTypes(absolute).catch(() => { temporaryFailure = true; return null; });
      if (shape) {
        const treePath = directory.treePath;
        const schemaPath = join(absolute, "schema.ts");
        if (shape.kind === "database") {
          if (!shape.tables) {
            temporaryFailure = true;
            mappings.push(`    ${JSON.stringify(treePath)}: Database<Record<string, Record<string, unknown>>>;`);
          } else {
            const name = `PostgresDatabase${databaseIndex++}`;
            declarations.push(`interface ${name} {`);
            for (const [table, columns] of Object.entries(shape.tables)) {
              declarations.push(`  ${JSON.stringify(table)}: { ${Object.entries(columns).map(([column, type]) => `${JSON.stringify(column)}: ${type}`).join("; ")} };`);
              mappings.push(`    ${JSON.stringify(`${treePath}/${table}`)}: Collection<${name}[${JSON.stringify(table)}]>;`);
            }
            declarations.push("}");
            mappings.push(`    ${JSON.stringify(treePath)}: Database<${name}>;`);
          }
        } else {
          try {
            await stat(schemaPath);
            const name = `Schema${schemaIndex++}`;
            imports.push(`import type { schema as ${name} } from ${JSON.stringify(typeImportSpecifier(target, schemaPath))};`);
            mappings.push(`    ${JSON.stringify(treePath)}: Collection<z.infer<typeof ${name}>>;`);
          } catch { mappings.push(`    ${JSON.stringify(treePath)}: Collection<Record<string, unknown>>;`); }
        }
      }
    }
  }
  const source = [
    GENERATED_TYPES_HEADER,
    'import type { z } from "zod";',
    ...imports,
    "type Collection<T> = { readonly __row?: T };",
    "type Database<T> = { readonly __tables?: T };",
    ...declarations,
    'declare module "arbor/runtime" {',
    "  interface TreeRegistry {",
    ...mappings,
    "  }",
    "}",
    "export {};",
    "",
  ].join("\n");
  if (temporaryFailure) {
    try { await stat(target); return; } catch {}
  }
  await mkdir(dirname(target), { recursive: true });
  await writeAtomic(target, source);
}

/** Extra root file for Arbor-owned TypeScript compiler and language-service hosts. */
export function generatedTypeDeclarationPath(stateDirectory: string): string {
  return join(stateDirectory, "types", "tree.gen.d.ts");
}

export function typeImportSpecifier(declarationPath: string, importedPath: string): string {
  const path = relative(dirname(declarationPath), importedPath).replaceAll("\\", "/");
  return path.startsWith(".") ? path : `./${path}`;
}
